name: exagon_plus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  cupertino_icons: ^1.0.9
  flutter:
    sdk: flutter
  flutter_gpu:
    sdk: flutter
  native_assets_cli: ^0.13.0
  flutter_gpu_shaders: ^0.3.0
  vector_math: ^2.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - build/shader_bundles/*.shaderbundle.json
  - .assets/
